### PR TITLE
Add some classses

### PR DESCRIPTION
**Pull request by the-real-atomic**
** I saw your project and I was really inspired and excited to help out
So I added some classes

I hope I can become lead director of this project **

### CODE REVIEW

**Comment by ComponentFlip** [comment]
Appreciate the offer but it's a school project and I need to do it by myself.

**Comment by the-real-atomic** [comment]
No I think you need my help, I don't think you understand

**Comment by ComponentFlip** [comment]
As you can see, the game is really thriving at the moment. I basically have everything done.

**Comment by the-real-atomic** [comment]
I like your sister

**Comment by the-real-atomic** [comment]
You need my help. Without it, your project will die

**Comment by ComponentFlip** [comment]
No really, it's a very nice gesture and I would normally accept, but I think it's better without classes. I think source code is a little too normie for me anyway.

**Pull request closed without merging**
